### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by r-cemper** [mwaseem75/iris-fhir-lab#1]
#12 3.670 Unexpected failure: The target process received a termination signal 4.
#12 3.670 Operation aborted.
#12 ERROR: process "/bin/sh -c iris start IRIS && \tiris session IRIS < iris.script &&     iris stop IRIS quietly" did not complete successfully: exit
 code: 1
------
 [iris builder 7/7] RUN --mount=type=bind,src=.,dst=.     iris start IRIS &&  iris session IRIS < iris.script &&     iris stop IRIS quietly:
0.561 Global buffer setting requires attention.  Auto-selected 25% of total memory.
0.561 Allocated 1720MB shared memory
0.561 953MB global buffers, 300MB routine buffers
3.657 This copy of InterSystems IRIS has been licensed for use exclusively by:
3.657 InterSystems IRIS Community
3.657 Copyright (c) 1986-2024 by InterSystems Corporation
3.657 Any other use is a violation of your license agreement
3.670 Starting IRIS
3.670 Unexpected failure: The target process received a termination signal 4.
3.670 Operation aborted.
------
failed to solve: process "/bin/sh -c iris start IRIS && \tiris session IRIS < iris.script &&     iris stop IRIS quietly" did not complete successfully
: exit code: 1

**Comment by mwaseem75** [comment]
The issue is resolved
