### ISSUE TITLE
Solution.Install call to SubmitResourceFiles() assumes Container folder location

### ISSUE THREAD

**Issue by tanifgit** [mwaseem75/iris-fhir-lab#3]
In Solution.Install:Run() the method attempts to load FHIR Resources, via a call to SubmitResourceFiles() -
`zw ##class(HS.FHIRServer.Tools.DataLoader).SubmitResourceFiles("/opt/irisapp/src/fhirdata", "FHIRSERVER", appKey)`
But the location used /opt will be relevant for the Docker sample, (most probably) not for a direct install via ZPM/IPM.
Should probably make this configurable.

**Comment by mwaseem75** [comment]
FHIR Resources are loading successfully.
